# Generated by Django 5.2.12 on 2026-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0039_signing_keys'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagereleasecomponent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='installerpackage',
            name='architecture_variant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='architecture_variant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='packagereleasecomponent',
            name='index_architecture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasearchitecture',
            name='base_architecture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasearchitecture',
            name='variant_architecture',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasecomponent',
            unique_together={('package', 'release_component', 'index_architecture', '_pulp_domain')},
        ),
    ]
